# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-03 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='InterviewNo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
