# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20160703_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='Post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.Post'),
            preserve_default=False,
        ),
    ]
