# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-04 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_interview_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Post_Dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Personal')),
                ('Post_Dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Post_Dept')),
            ],
        ),
        migrations.RemoveField(
            model_name='interview',
            name='Post',
        ),
        migrations.AddField(
            model_name='subqul_post',
            name='Subject',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
