# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-05 07:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_interview_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='DeptPost',
        ),
    ]
