# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-07 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_personal_deptpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
