# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_interview_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_interview_viewer',
            name='Status',
        ),
        migrations.AddField(
            model_name='personal_interview',
            name='Status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.CV_Status'),
        ),
    ]
