# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160708_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='InterviewNo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
