# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 15:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='Post_Dept',
        ),
    ]
