# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-18 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_vacancy_post_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience_for_post',
            name='Person',
        ),
        migrations.RemoveField(
            model_name='experience_for_post',
            name='Post',
        ),
        migrations.DeleteModel(
            name='Experience_For_Post',
        ),
    ]
