# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 15:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160619_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='DateOfPublish',
            field=models.DateField(blank=True, default=datetime.datetime(2016, 6, 19, 15, 25, 40, 400810)),
        ),
    ]
