# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-19 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160619_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='DateOfPublish',
            field=models.DateField(default=b'2016-06-19'),
        ),
    ]
