# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ermsapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('UName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=3)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('AdminID', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('University', models.CharField(max_length=30)),
                ('Degree', models.CharField(max_length=30)),
                ('DegreeType', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DeptName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('UName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=3)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('HODID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HR',
            fields=[
                ('UName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=3)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('HRID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('Date', models.DateField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Department')),
                ('HOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.HOD')),
            ],
        ),
        migrations.CreateModel(
            name='Interviewers',
            fields=[
                ('UName', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=3)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('InterviewerID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('NoOfInts', models.PositiveIntegerField()),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Interviewers_SpecializedArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Interviewers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Interviewers')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterviewType', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NIC', models.PositiveIntegerField(unique=True)),
                ('FName', models.CharField(max_length=30)),
                ('LName', models.CharField(max_length=30)),
                ('FullName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Nationality', models.CharField(max_length=20)),
                ('CVImage', models.FileField(upload_to=ermsapp.models.user_directory_path)),
                ('Department', models.ManyToManyField(to='ermsapp.Department')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.DateField()),
                ('Experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Experience')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Person_Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Post', models.CharField(max_length=100)),
                ('NoOfInterviews', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Post_Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.DateField()),
                ('SpecialNotes', models.TextField()),
                ('GPA', models.FloatField()),
                ('DegreeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Degree')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Duration', models.DateField()),
                ('Experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Experience')),
                ('Person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Post_IntType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InterviewTypeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.InterviewType')),
                ('PostID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Qualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QName', models.CharField(max_length=100)),
                ('Result', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SpecializedArea',
            fields=[
                ('SpecializedAreaID', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('SpecializedArea', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubQualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(max_length=200)),
                ('SubResult', models.CharField(max_length=4)),
                ('SubWiseResQualifications', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Qualifications')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfPublish', models.DateField()),
                ('ClosingDate', models.DateField()),
                ('NoOfIntDone', models.IntegerField()),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Department')),
                ('NextInterview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post_IntType')),
                ('Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HallName', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='Experience',
            field=models.ManyToManyField(through='ermsapp.Post_Experience', to='ermsapp.Experience'),
        ),
        migrations.AddField(
            model_name='post',
            name='InterviewType',
            field=models.ManyToManyField(through='ermsapp.Post_IntType', to='ermsapp.InterviewType'),
        ),
        migrations.AddField(
            model_name='person_qualifications',
            name='Qualifications',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Qualifications'),
        ),
        migrations.AddField(
            model_name='person',
            name='Experience',
            field=models.ManyToManyField(through='ermsapp.Person_Experience', to='ermsapp.Experience'),
        ),
        migrations.AddField(
            model_name='person',
            name='Post',
            field=models.ManyToManyField(to='ermsapp.Post'),
        ),
        migrations.AddField(
            model_name='person',
            name='Qualifications',
            field=models.ManyToManyField(through='ermsapp.Person_Qualifications', to='ermsapp.Qualifications'),
        ),
        migrations.AddField(
            model_name='interviewers_specializedarea',
            name='SpecializedArea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.SpecializedArea'),
        ),
        migrations.AddField(
            model_name='interviewers',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post'),
        ),
        migrations.AddField(
            model_name='interviewers',
            name='SpecializedArea',
            field=models.ManyToManyField(through='ermsapp.Interviewers_SpecializedArea', to='ermsapp.SpecializedArea'),
        ),
        migrations.AddField(
            model_name='interview',
            name='InterviewType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.InterviewType'),
        ),
        migrations.AddField(
            model_name='interview',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post'),
        ),
        migrations.AddField(
            model_name='interview',
            name='Vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Vacancy'),
        ),
        migrations.AddField(
            model_name='interview',
            name='Venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Venue'),
        ),
        migrations.AddField(
            model_name='hr',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post'),
        ),
        migrations.AddField(
            model_name='hod',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post'),
        ),
        migrations.AddField(
            model_name='degree',
            name='Post_Degree',
            field=models.ManyToManyField(through='ermsapp.Post_Degree', to='ermsapp.Post'),
        ),
        migrations.AddField(
            model_name='admin',
            name='Department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Department'),
        ),
        migrations.AddField(
            model_name='admin',
            name='Post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ermsapp.Post'),
        ),
    ]
